
# Базовые правила
disabled_rules:
  - trailing_whitespace
#  - line_length
#  - identifier_name
  - comment_spacing
  - private_over_fileprivate
  - multiple_closures_with_trailing_closure
  

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping

# Исключенные директории
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData

# Настройки правил
line_length: 160
function_body_length: 200
type_body_length: 400
file_length: 800
function_parameter_count:
  warning: 6
  error: 8

# Пользовательские правила
#custom_rules:
#  no_print:
#    name: "No Print"
#    regex: "print\\("
#    message: "Используйте Logger вместо print"
#    severity: warning

analyzer_rules:
  - unused_import
  - unused_declaration

identifier_name:
  min_length:
    error: 1      # Ошибка только для пустых имен
    warning: 2    # Предупреждение для очень коротких
  max_length: 40
  excluded:       # Исключения для общепринятых
    - i
    - j
    - k
    - x
    - y
    - z
    - id
    - url
    - uri

